spring.application.name=todo

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=Muny
spring.datasource.password=Muny168168

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true