spring.application.name=todo

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=Muny
spring.datasource.password=Muny168168

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

# JWT Configuration
# WARNING: Change this secret before deploying to production!
# It must be at least 256 bits (32 characters) for HS256
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
